import type { Metadata } from "next";
import { Inter } from "next/font/google"; // Changed to Inter
import "./globals.css";
import { MSWProvider } from '../components/MSWProvider'; // Import MSWProvider
import { AuthProvider } from '../context/AuthContext'; // Import AuthProvider

const inter = Inter({ subsets: ["latin"] }); // Using Inter font

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}> {/* Using Inter font class */}
        <MSWProvider>
          <AuthProvider>{children}</AuthProvider> {/* Wrap children with AuthProvider */}
        </MSWProvider>
      </body>
    </html>
  );
}
